name: quagga_dart
description: Port of QuaggaJs library
version: 0.0.2
author: Hadrien Lejard <hadrien.lejard@gmail.com>
homepage: https://github.com/lejard-h/quagga_dart

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
